name: simple_counter_app
description: A simple Flutter counter application.
publish_to: 'none'

environment:
  sdk: '^3.32.8'

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true